# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIFileListWindow.ui'
#
# Created: Sun Jan 27 10:03:02 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MusicFileListWindow(object):
    def setupUi(self, MusicFileListWindow):
        MusicFileListWindow.setObjectName(_fromUtf8("MusicFileListWindow"))
        MusicFileListWindow.resize(646, 600)
        self.centralwidget = QtGui.QWidget(MusicFileListWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.startPauseButton = QtGui.QPushButton(self.frame)
        self.startPauseButton.setGeometry(QtCore.QRect(60, 0, 41, 27))
        self.startPauseButton.setObjectName(_fromUtf8("startPauseButton"))
        self.previousSongButton = QtGui.QPushButton(self.frame)
        self.previousSongButton.setGeometry(QtCore.QRect(20, 0, 41, 27))
        self.previousSongButton.setObjectName(_fromUtf8("previousSongButton"))
        self.nextSongButton = QtGui.QPushButton(self.frame)
        self.nextSongButton.setGeometry(QtCore.QRect(140, 0, 41, 27))
        self.nextSongButton.setObjectName(_fromUtf8("nextSongButton"))
        self.masterVolumeSlider = QtGui.QSlider(self.frame)
        self.masterVolumeSlider.setGeometry(QtCore.QRect(470, 10, 160, 19))
        self.masterVolumeSlider.setMaximum(100)
        self.masterVolumeSlider.setSliderPosition(50)
        self.masterVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.masterVolumeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.masterVolumeSlider.setObjectName(_fromUtf8("masterVolumeSlider"))
        self.songPositionSlider = QtGui.QSlider(self.frame)
        self.songPositionSlider.setGeometry(QtCore.QRect(20, 30, 171, 19))
        self.songPositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.songPositionSlider.setObjectName(_fromUtf8("songPositionSlider"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 53, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.stopButton = QtGui.QPushButton(self.frame)
        self.stopButton.setGeometry(QtCore.QRect(100, 0, 41, 27))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.songFrame = QtGui.QFrame(self.centralwidget)
        self.songFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.songFrame.setFrameShape(QtGui.QFrame.Panel)
        self.songFrame.setObjectName(_fromUtf8("songFrame"))
        self.songDetailsFrame = QtGui.QFrame(self.songFrame)
        self.songDetailsFrame.setGeometry(QtCore.QRect(10, 10, 341, 80))
        self.songDetailsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.songDetailsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.songDetailsFrame.setObjectName(_fromUtf8("songDetailsFrame"))
        self.songNameLabel = QtGui.QLabel(self.songDetailsFrame)
        self.songNameLabel.setGeometry(QtCore.QRect(10, 10, 151, 17))
        self.songNameLabel.setObjectName(_fromUtf8("songNameLabel"))
        self.songControlFrame = QtGui.QFrame(self.songFrame)
        self.songControlFrame.setGeometry(QtCore.QRect(360, 10, 271, 80))
        self.songControlFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.songControlFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.songControlFrame.setObjectName(_fromUtf8("songControlFrame"))
        self.label = QtGui.QLabel(self.songControlFrame)
        self.label.setGeometry(QtCore.QRect(20, 10, 53, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.songControlFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 53, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.songControlFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 53, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.songTempoSlider = QtGui.QSlider(self.songControlFrame)
        self.songTempoSlider.setGeometry(QtCore.QRect(80, 50, 181, 20))
        self.songTempoSlider.setMinimum(-100)
        self.songTempoSlider.setMaximum(100)
        self.songTempoSlider.setProperty("value", 0)
        self.songTempoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.songTempoSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.songTempoSlider.setObjectName(_fromUtf8("songTempoSlider"))
        self.songPitchSlider = QtGui.QSlider(self.songControlFrame)
        self.songPitchSlider.setGeometry(QtCore.QRect(80, 30, 181, 20))
        self.songPitchSlider.setMinimum(-1000)
        self.songPitchSlider.setMaximum(1000)
        self.songPitchSlider.setProperty("value", 0)
        self.songPitchSlider.setSliderPosition(0)
        self.songPitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.songPitchSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.songPitchSlider.setTickInterval(100)
        self.songPitchSlider.setObjectName(_fromUtf8("songPitchSlider"))
        self.songVolumeSlider = QtGui.QSlider(self.songControlFrame)
        self.songVolumeSlider.setGeometry(QtCore.QRect(80, 10, 181, 20))
        self.songVolumeSlider.setMaximum(150)
        self.songVolumeSlider.setProperty("value", 100)
        self.songVolumeSlider.setTracking(True)
        self.songVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.songVolumeSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.songVolumeSlider.setObjectName(_fromUtf8("songVolumeSlider"))
        self.gridLayout_2.addWidget(self.songFrame, 2, 0, 1, 1)
        MusicFileListWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MusicFileListWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MusicFileListWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MusicFileListWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MusicFileListWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MusicFileListWindow)
        QtCore.QObject.connect(self.startPauseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MusicFileListWindow.startPausedClicked)
        QtCore.QObject.connect(self.previousSongButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MusicFileListWindow.previousSong)
        QtCore.QObject.connect(self.nextSongButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MusicFileListWindow.nextSong)
        QtCore.QObject.connect(self.tableWidget, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MusicFileListWindow.rowDoubleClicked)
        QtCore.QObject.connect(self.masterVolumeSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MusicFileListWindow.volumeSliderMoved)
        QtCore.QObject.connect(self.songVolumeSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MusicFileListWindow.songVolumeSliderMoved)
        QtCore.QObject.connect(self.songPitchSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MusicFileListWindow.songPitchSliderMoved)
        QtCore.QObject.connect(self.songTempoSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MusicFileListWindow.songTempoSliderMoved)
        QtCore.QObject.connect(self.songPositionSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MusicFileListWindow.songPositionSliderMoved)
        QtCore.QMetaObject.connectSlotsByName(MusicFileListWindow)

    def retranslateUi(self, MusicFileListWindow):
        MusicFileListWindow.setWindowTitle(QtGui.QApplication.translate("MusicFileListWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.startPauseButton.setText(QtGui.QApplication.translate("MusicFileListWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.previousSongButton.setText(QtGui.QApplication.translate("MusicFileListWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.nextSongButton.setText(QtGui.QApplication.translate("MusicFileListWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MusicFileListWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MusicFileListWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MusicFileListWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MusicFileListWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MusicFileListWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MusicFileListWindow", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MusicFileListWindow", "Tempo", None, QtGui.QApplication.UnicodeUTF8))
        self.songNameLabel.setText(QtGui.QApplication.translate("MusicFileListWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MusicFileListWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MusicFileListWindow", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MusicFileListWindow", "Tempo", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MusicFileListWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MusicFileListWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))

